source 'https://rubygems.org'

ruby '2.6.3'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'minitest'
gem 'rubocop'
gem 'erubis'
gem 'rack'
gem 'rack-protection'
gem 'rack-test'
gem 'rake'
gem 'tilt'
group :production do 
  gem "puma"
end